import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Providers } from "./components/Providers";
import { AuthenticationWrapper } from "./components/AuthenticationWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <AuthenticationWrapper>
        <html lang="en" data-theme="mytheme">
          <body className={`antialiased bg-base-200`}>
            <Navbar>
              <div className="mx-8 mt-8">
                {children}
              </div>
            </Navbar>
          </body>
        </html>
      </AuthenticationWrapper>
    </Providers>
  );
}
